gitlab CI updates

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -14,6 +14,8 @@ services:
   - docker:24-dind  # Enable Docker-in-Docker for Docker functionality
 
 before_script:
+  - echo "Installing Docker CLI in the main container"
+  - apt-get update && apt-get install -y docker.io || { echo "Failed to install Docker CLI"; exit 1; }
   - echo "Checking if Homebrew is installed"
   - if ! command -v brew &>/dev/null; then
       echo "Installing Homebrew";
