gitlab CI updates

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -13,6 +13,9 @@ default:
   image: docker:latest  # Use Docker's official image with Docker support
 
 before_script:
+  # Install curl and bash if they are not already installed
+  - echo "Checking if curl and bash are installed"
+  - apt-get update && apt-get install -y curl bash || { echo "Failed to install curl or bash"; exit 1; }
   - echo "Checking if Homebrew is installed"
   - if ! command -v brew &>/dev/null; then
       echo "Installing Homebrew";
